name: GitHub Pages Deploy
on:
    push:
        branches:
            # Only default branch
            - main
        paths:
            # Only on changes to "public/" and GitHub Pages action
            - 'public/**'
            - .github/workflows/github-pages.yml

jobs:
    Deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository code
              uses: actions/checkout@v2
            - name: Push "public/" changes to "gh-pages" branch
              run: git push origin `git subtree split --prefix public/ main`:refs/heads/gh-pages --force
